AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  website

  Sample SAM Template for website

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  VisitorCountFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: visitor_count/
      Handler: VisitorCount.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref VisitorCountTable
      Environment:
        Variables:
          DB_NAME: !Ref VisitorCountTable
          AWS_SAM_STACK_NAME: website
      Events:
        VisitorCount:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /visitorcount
            Method: post
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: visitor-count-id
          AttributeType: S
      KeySchema:
        - AttributeName: visitor-count-id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VisitorCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Visitor Count function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitorcount/"
  VisitorCountFunction:
    Description: "Visitor Count Lambda Function ARN"
    Value: !GetAtt VisitorCountFunction.Arn
  VisitorCountFunctionIamRole:
    Description: "Implicit IAM Role created for Visitor Count function"
    Value: !GetAtt VisitorCountFunctionRole.Arn
