on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: aws-actions/setup-sam@v2
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::205930627269:role/GithubActionsIAMRole
          role-session-name: sam-role-session
          aws-region: ${{ env.AWS_REGION }}
      # sam build
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here
      - name: install Python modules
        run: pip install -r tests/requirements.txt --user
      - name: run unit tests
        run: pytest -v tests/unit
# sam deploy stage
      - run: sam deploy --config-env stage
      - name: run integration tests
        run: AWS_SAM_STACK_NAME="website-stage" pytest -v tests/integration
      - name: cleanup staging
        run: sam delete --stack-name "website-stage"
      - run: sam deploy --config-env prod
